---
# Custom sysctl value handling has been implemented into the common role

# - name: Set sysctl values for Redis node
#   ansible.posix.sysctl:
#     name: "{{ item.name }}"
#     value: "{{ item.value }}"
#     state: present
#   loop:
#     "{{ sysctl_values }}"

- name: Redis tasks
  ansible.builtin.import_tasks: redis.yml
