---
- name: install redis packages
  ansible.builtin.apt:
    name: redis-server
    state: present
    update_cache: yes

- name: configure redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    mode: "0640"
  notify: restart redis
