---
dependencies:
  - role: arillso.logrotate
    vars:
      logrotate_global_config: false
      logrotate_applications:
        - name: cron_opennemas
          definitions:
            - logs:
                - /home/opennemas/shared/tmp/logs/cron.log
              options:
                - su www-data www-data
                - maxsize 500M
                - compress
                - compresscmd /bin/gzip
                - dateext
                - daily
                - rotate 7
                - missingok
                - copytruncate

  - role: gabops.papertrail
    vars:
      papertrail_version: "0.20"
      papertrail_service_enabled: true
      papertrail_service_state: started
      papertrail_check_download_certs: true
      papertrail_managed_conf_file: true
      papertrail_managed_conf_file_owner: root
      papertrail_managed_conf_file_group: root
      papertrail_managed_conf_file_mode: "0644"
      papertrail_managed_conf_file_backup: false
      papertrail_custom_hostname: ""
      papertrail_destination_host: "{{ onm_papertrail_destination_host }}"
      papertrail_destination_port: "{{ onm_papertrail_destination_port }}"
      papertrail_destination_protocol: "{{ onm_papertrail_destination_protocol }}"
      papertrail_log_facility: ""
      papertrail_log_severity: ""
      papertrail_new_file_check_interval: ""
      papertrail_exclude_patterns: []
      papertrail_files_to_exclude: []
      papertrail_files_to_log: "{{ onm_papertrail_files_to_log }}"
      
  - role: oefenweb.postfix
    vars:
      postfix_aliases: 
        - user: "{{ postfix_config.recipient_user }}"
          alias: "{{ postfix_config.recipient }}"

      postfix_relayhost: "{{ postfix_config.relayhost }}"
      postfix_relayhost_port: "{{ postfix_config.relayport }}"

      postfix_sasl_user: "{{ postfix_config.sasl_user }}"
      postfix_sasl_password: "{{ postfix_config.sasl_pass }}"

      postfix_smtp_tls_security_level: "{{ postfix_config.smtp_tls_security_level }}"
      
      postfix_compatibility_level: 2

      postfix_raw_options: []