---
php_packages:
  - curl
  - gettext
  - mysql-client
  - nfs-common
  - php7.3-bcmath
  - php7.3-cli
  - php7.3-common
  - php7.3-curl
  - php7.3-fpm
  - php7.3-gettext
  - php7.3-igbinary
  - php7.3-imagick
  - php7.3-intl
  - php7.3-json
  - php7.3-mbstring
  - php7.3-mysql
  - php7.3-opcache
  - php7.3-readline
  - php7.3-redis
  - php7.3-xml
  - php7.3-xsl
  - php7.3-zip

php_unix_socket: "/var/run/php7.3-fpm.sock"

php_cli_ini:
  - directive: "serialize_precision"
    value: "17"
  - directive: "memory_limit"
    value: "512M"
  - directive: "default_charset"
    value: "\"UTF-8\""
  - directive: "mail.add_x_header"
    value: "On"

php_fpm_ini:
  - directive: "serialize_precision"
    value: "17"
  - directive: "expose_php"
    value: "On"
  - directive: "max_execution_time"
    value: "60"
  - directive: "memory_limit"
    value: "512M"
  - directive: "post_max_size"
    value: "20M"
  # - directive: "default_charset"
  #   value: "\"UTF-8\""
  - directive: "upload_max_filesize"
    value: "20M"
  - directive: "mail.add_x_header"
    value: "On"

php_fpm_conf:
  - directive: "emergency_restart_threshold"
    value: "10"
  - directive: "emergency_restart_interval"
    value: "1m"
  - directive: "process_control_timeout"
    value: "5s"

php_www_conf:
  - directive: "listen.backlog"
    value: "65535"
  - directive: "pm"
    value: "ondemand"
  - directive: "pm.max_children"
    value: "50"
  - directive: "pm.process_idle_timeout"
    value: "5s;"
  - directive: "pm.max_requests"
    value: "1500"
  # - directive: "pm.status_path"
  #   value: "/status"
  - directive: "request_terminate_timeout"
    value: "60s"
  - directive: "rlimit_files"
    value: "131072"
  - directive: "rlimit_core"
    value: "unlimited"
  - directive: "chdir"
    value: "/"
  - directive: "listen"
    value: "{{ php_unix_socket }}"

php_opcache_ini:
  - directive: "zend_extension"
    value: "opcache.so"
  - directive: "opcache.enable"
    value: "1"
  - directive: "opcache.enable_cli"
    value: "0"
  - directive: "opcache.memory_consumption"
    value: "256"
  # - directive: "opcache.interned_strings_buffer"
  #   value: "128"
  - directive: "opcache.max_accelerated_files"
    value: "50000"
  - directive: "opcache.revalidate_freq"
    value: "5"
  - directive: "opcache.fast_shutdown"
    value: "1"
  - directive: "opcache.max_wasted_percentage"
    value: "5"
  - directive: "opcache.use_cwd"
    value: "1"
  - directive: "opcache.validate_timestamps"
    value: "1"
