---
- name: Reload php-fpm
  ansible.builtin.service:
    name: php7.3-fpm
    state: reloaded

- name: Delete doctrine cache
  ansible.builtin.file:
    path: /home/opennemas/current/tmp/cache
    state: absent
