---
- name: reload php-fpm
  ansible.builtin.service:
    name: php7.3-fpm
    state: reloaded

# - name: delete doctrine cache
#   ansible.builtin.file:
#     path: /home/my_app/current/tmp/cache
#     state: absent
