---
dependencies:
  - role: arillso.logrotate
    vars:
      logrotate_global_config: false # TODO: check if correct
      logrotate_applications:
        - name: application_opennemas
          definitions:
            - logs:
                - /home/opennemas/shared/tmp/logs/application.log
              options:
                - su www-data www-data
                - maxsize 500M
                - compress
                - compresscmd /bin/gzip
                - dateext
                - daily
                - rotate 7
                - missingok
                - copytruncate
        - name: manager_error_opennemas
          definitions:
            - logs:
                - /home/opennemas/shared/tmp/logs/manager-error.log
              options:
                - su www-data www-data
                - maxsize 500M
                - compress
                - compresscmd /bin/gzip
                - dateext
                - daily
                - rotate 7
                - missingok
                - postrotate
                - "[ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`"
                - endscript
        - name: error_opennemas
          definitions:
            - logs:
                - /home/opennemas/shared/tmp/logs/opennemas-error.log
              options:
                - su www-data www-data
                - maxsize 500M
                - compress
                - compresscmd /bin/gzip
                - dateext
                - daily
                - rotate 7
                - missingok
                - copytruncate
                - postrotate
                - "[ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`"
                - endscript
        - name: prod_opennemas
          definitions:
            - logs:
                - /home/opennemas/shared/tmp/logs/prod.log
              options:
                - su www-data www-data
                - maxsize 500M
                - compress
                - compresscmd /bin/gzip
                - dateext
                - daily
                - rotate 7
                - missingok
                - copytruncate