---
essential_packages:
  - aptitude
  - ntp
  - vim
  - byobu
  - conntrack

locales:
  - en_US.UTF-8
  - gl_ES.UTF-8
  - es_ES.UTF-8
  - ca_ES.UTF-8

admin_key_name: admin

# ansible_port: 22

# # This variable is added to avoid confusion and increase readability
# # when referencing the variable containing the ssh port, which is
# # the same as the ansible port
# ssh_port: "{{ ansible_port }}"