---
# This is needed to avoid having to parse the groups which a node belongs to
servers:
  # 'first' filter is needed for lists that will only have one element
  sto: "{{ groups.sto | first }}"
  dbr: "{{ groups.dbr | first }}"
  dba: "{{ groups.dba | first }}"
  wrk: "{{ groups.wrk | first }}"
  app: "{{ groups.app }}"
  lbl: "{{ groups.lbl }}"
