sysctl_values:
  - name: fs.file-max
    value: 3263046
  - name: vm.dirty_ratio
    value: 60
  - name: vm.dirty_background_ratio
    value: 2
  - name: vm.overcommit_memory
    value: 2
  - name: vm.overcommit_ratio
    value: 100
  - name: net.ipv4.tcp_syncookies
    value: 1
  - name: net.ipv4.conf.all.accept_source_route
    value: 0
  - name: net.ipv4.conf.default.accept_source_route
    value: 0
  - name: net.ipv4.conf.default.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv4.tcp_synack_retries
    value: 2
  - name: net.ipv4.ip_local_port_range
    value: 2000 65535
  - name: net.ipv4.tcp_rfc1337
    value: 1
  - name: net.ipv4.tcp_fin_timeout
    value: 20
  - name: net.ipv4.tcp_keepalive_intvl
    value: 30
  - name: net.ipv4.tcp_keepalive_probes
    value: 5
  - name: net.ipv4.tcp_keepalive_time
    value: 600
  - name: net.ipv4.conf.all.rp_filter
    value: 1
  - name: net.core.somaxconn
    value: 65535
  - name: net.core.netdev_max_backlog
    value: 65535
  - name: net.ipv4.tcp_max_syn_backlog
    value: 7000
  - name: net.ipv4.conf.all.log_martians
    value: 1
  - name: net.ipv4.conf.default.log_martians
    value: 1
  - name: net.netfilter.nf_conntrack_tcp_timeout_last_ack
    value: 120
  - name: net.netfilter.nf_conntrack_tcp_timeout_established
    value: 200
  - name: net.netfilter.nf_conntrack_max
    value: 524288
  - name: net.core.rmem_default
    value: 31457280
  - name: net.core.rmem_max
    value: 12582912
  - name: net.core.wmem_default
    value: 31457280
  - name: net.core.wmem_max
    value: 12582912
  - name: net.core.optmem_max
    value: 25165824
  - name: net.ipv4.tcp_mem
    value: 769389  1025852 1538778
  - name: net.ipv4.udp_mem
    value: 769389 1025852 1538778
  - name: net.ipv4.tcp_rmem
    value: 10240 87380 12582912
  - name: net.ipv4.udp_rmem_min
    value: 16384
  - name: net.ipv4.tcp_wmem
    value: 10240 87380 12582912
  - name: net.ipv4.udp_wmem_min
    value: 16384
  - name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
  - name: net.ipv4.tcp_tw_reuse
    value: 0
