---
sysctl_values:
  # Increase size of file handles and inode cache
  - name: fs.file-max
    value: 3263046
  
# Start Memory
  - name: vm.dirty_ratio
    value: 60
  - name: vm.dirty_background_ratio
    value: 2
  - name: vm.overcommit_memory
    value: 2
  - name: vm.overcommit_ratio
    value: 100
# End Memory
  
# Start Network 
  # This sets the kernel to use the SYN cookies mechanism (SYN flooding protection)
  - name: net.ipv4.tcp_syncookies
    value: 1

  # Dropping Source Routed Packets
  - name: net.ipv4.conf.all.accept_source_route
    value: 0
  - name: net.ipv4.conf.default.accept_source_route
    value: 0
  
  # Drop ICMP redirect messages
  - name: net.ipv4.conf.default.accept_redirects
    value: 0
  - name: net.ipv4.conf.all.accept_redirects
    value: 0
  
  # Dont Send ICMP redirect messages
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  
  # Number of times SYNACKs for passive TCP connection
  # (to keep half-open connections in the queue (3 equates to roughly 45 seconds))
  - name: net.ipv4.tcp_synack_retries
    value: 2
  
  # Allowed local port range
  - name: net.ipv4.ip_local_port_range
    value: 2000 65535
  
  # Protect Against TCP Time-Wait # OSO-101 
  - name: net.ipv4.tcp_rfc1337
    value: 1
  
  # Time to hold socket in state FIN-WAIT-2
  - name: net.ipv4.tcp_fin_timeout
    value: 20
  
  # Decrease the time default value for connections to keep alive
  - name: net.ipv4.tcp_keepalive_intvl
    value: 30
  - name: net.ipv4.tcp_keepalive_probes
    value: 5
  - name: net.ipv4.tcp_keepalive_time
    value: 600
  
  # Enable source address spoofing protection
  - name: net.ipv4.conf.all.rp_filter
    value: 1
  
  # Increase number of incoming connections
  - name: net.core.somaxconn
    value: 65535
  
  # Increase number of incoming connections backlog
  - name: net.core.netdev_max_backlog
    value: 65535
  
  # Use a backlog queue size of 2048 connections
  - name: net.ipv4.tcp_max_syn_backlog
    value: 7000
  
  # Enable logging of packets with forged source addresses
  - name: net.ipv4.conf.all.log_martians
    value: 1
  - name: net.ipv4.conf.default.log_martians
    value: 1
  
  # Wait 1min seg until close socket
  - name: net.netfilter.nf_conntrack_tcp_timeout_last_ack
    value: 120
  - name: net.netfilter.nf_conntrack_tcp_timeout_established
    value: 200
  
  # Num of connections allow by iptables
  - name: net.netfilter.nf_conntrack_max
    value: 524288
  
  # Default Socket Receive Buffer
  - name: net.core.rmem_default
    value: 31457280
  
  # Maximum Socket Receive Buffer
  - name: net.core.rmem_max
    value: 12582912
  
  # Default Socket Send Buffer
  - name: net.core.wmem_default
    value: 31457280
  
  # Maximum Socket Send Buffer
  - name: net.core.wmem_max
    value: 12582912
  
  # Increase the maximum amount of option memory buffers
  - name: net.core.optmem_max
    value: 25165824
  
  # Increase the maximum total buffer-space allocatable
  # This is measured in units of pages (4096 bytes)
  - name: net.ipv4.tcp_mem
    value: 769389  1025852 1538778
  - name: net.ipv4.udp_mem
    value: 769389 1025852 1538778
  
  # Increase the read-buffer space allocatable
  - name: net.ipv4.tcp_rmem
    value: 10240 87380 12582912
  - name: net.ipv4.udp_rmem_min
    value: 16384
  
  # Increase the write-buffer-space allocatable
  - name: net.ipv4.tcp_wmem
    value: 10240 87380 12582912
  - name: net.ipv4.udp_wmem_min
    value: 16384
  
  # Increase the tcp-time-wait buckets pool size to prevent simple DOS attacks
  - name: net.ipv4.tcp_max_tw_buckets
    value: 1440000
  - name: net.ipv4.tcp_tw_reuse
    value: 0
# End network