---
- name: Install dependencies
  ansible.builtin.package:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Install mysql-server packages
  ansible.builtin.package:
    name: mysql-server
    state: present
    update_cache: yes

- name: Include variables for mysql-related tasks
  ansible.builtin.include_vars:
    file: mysql.yml

- name: Send mysqld configuration file
  ansible.builtin.template:
    src: templates/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "0644"
  notify: Restart mysql-server service

- name: Set root password
  community.mysql.mysql_user:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ vault_root_mysql_password }}"
    name: root
    password: "{{ vault_root_mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: yes

# If column privileges are used, the priv1,priv2 part must be exactly as returned
# by a SHOW GRANT statement.
# If not followed, the module will always report changes (as it does right now).
- name: Add 'onm-instances' mysql user (ALWAYS will report changes)
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ vault_root_mysql_password }}"
    name: onm-instances
    password: "{{ vault_onm_instances_mysql_password }}"
    host: '%'
    priv: '*.*:ALL,GRANT'
    state: present
  no_log: yes

- name: Check if netdata is installed
  ansible.builtin.stat:
    path: /opt/netdata/usr/sbin/netdata
  register: nd

# If column privileges are used, the priv1,priv2 part must be exactly as returned
# by a SHOW GRANT statement.
# If not followed, the module will always report changes (as it does right now).
- name: Create netdata mysql user if netdata is installed
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ vault_root_mysql_password }}"
    name: netdata
    password: "{{ vault_netdata_mysql_password }}"
    host: 'localhost'
    priv: '*.*:USAGE'
    state: present
  when: nd.stat.exists
  no_log: yes

- name: Send netdata mysql plugin configuration if netdata is installed
  ansible.builtin.template:
    src: templates/netdata_plugin_mysql.conf.j2
    dest: /opt/netdata/etc/netdata/python.d/mysql.conf
    owner: netdata
    group: netdata
    mode: "0644"
  when: nd.stat.exists
