---
- name: add deployer user
  ansible.builtin.user:
    name: deployer
    comment: Jenkins deploy account
    uid: 10005
    shell: /bin/bash
    state: present

- name: set authorized key for deployer user
  ansible.posix.authorized_key:
    user: deployer
    state: present
    key: "{{ lookup('file', '../keys/deployer.pub') }}"

- name: add sudo privileges to deployer user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/common
    create: yes
    mode: "0400"
    state: present
    regexp: "^deployer"
    line: "deployer  ALL=(ALL:ALL) NOPASSWD: /usr/sbin/service php7.3-fpm reload, /usr/local/bin/updaterepo, /usr/bin/apt-get update, /usr/bin/apt list --installed, /usr/bin/apt-get -y install, /usr/bin/apt-get -y remove"
    validate: /usr/sbin/visudo -cf %s
