---
- name: Include variables for directory-related tasks
  ansible.builtin.include_vars:
    file: directories.yml

- name: Create Opennemas app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
  loop:
    "{{ appworker_directories }}"
