---
- name: Include logrotate role
  ansible.builtin.include_role:
    name: arillso.logrotate
  vars:
    logrotate_global_config: false      # TODO: check if correct
    logrotate_applications:
      - name: "application_{{ cert_name }}"
        definitions:
          - logs:
              - "/home/{{ cert_name }}/shared/tmp/logs/application.log"
            options:
              - su www-data www-data
              - maxsize 500M
              - compress
              - compresscmd /bin/gzip
              - dateext
              - daily
              - rotate 7
              - missingok
              - copytruncate
      - name: "manager_error_{{ cert_name }}"
        definitions:
          - logs:
              - "/home/{{ cert_name }}/shared/tmp/logs/manager-error.log"
            options:
              - su www-data www-data
              - maxsize 500M
              - compress
              - compresscmd /bin/gzip
              - dateext
              - daily
              - rotate 7
              - missingok
              - postrotate
              - "[ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`"
              - endscript
      - name: "error_{{ cert_name }}"
        definitions:
          - logs:
              - "/home/{{ cert_name }}/shared/tmp/logs/{{ cert_name }}-error.log"
            options:
              - su www-data www-data
              - maxsize 500M
              - compress
              - compresscmd /bin/gzip
              - dateext
              - daily
              - rotate 7
              - missingok
              - copytruncate
              - postrotate
              - "[ ! -f /var/run/nginx.pid ] || kill -USR1 `cat /var/run/nginx.pid`"
              - endscript
      - name: "prod_{{ cert_name }}"
        definitions:
          - logs:
              - "/home/{{ cert_name }}/shared/tmp/logs/prod.log"
            options:
              - su www-data www-data
              - maxsize 500M
              - compress
              - compresscmd /bin/gzip
              - dateext
              - daily
              - rotate 7
              - missingok
              - copytruncate
