---
- name: install nfs server package
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: mount nfs drives
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop:
    "{{ mountpoints }}"
