---
- name: Ensure the nfs client is installed
  package:
    name: nfs-common
    state: latest

- name: Include appworker mountpoints variables
  include_vars: appworker_mountpoints.yml

- name: Mount NFS drives
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop:
    "{{ appworker_mountpoints }}"