---
- name: Ensure the nfs client is installed
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Include variables for mount-related tasks
  ansible.builtin.include_vars:
    file: mountpoints.yml

- name: Mount NFS drives
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop:
    "{{ mountpoints }}"
