---
- name: Install node.js
  ansible.builtin.package:
    name: "{{ appworker_nodejs_packages }}"
    state: present

- name: Install npm packages
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ appworker_npm_packages }}"
