---
- name: Install node.js
  package:
    name: "{{ appworker_nodejs_packages }}"
    state: present

- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ appworker_npm_packages }}"
