---
- name: check if nodejs is already installed
  ansible.builtin.stat:
    path: /usr/bin/node
  register: node

- name: download the nodejs repository script
  ansible.builtin.get_url:
    url: "{{ node_repo_script_url }}"
    dest: /tmp/node_repo_setup
  run_once: yes
  delegate_to: localhost
  when: not node.stat.exists
  become: no

- name: send the nodejs repository script
  ansible.builtin.copy:
    src: /tmp/node_repo_setup
    dest: /tmp/node_repo_setup
    owner: root
    group: root
    mode: "0500"
  when: not node.stat.exists

- name: run the nodejs repository script
  ansible.builtin.command:
    cmd: /tmp/node_repo_setup
  when: not node.stat.exists

- name: delete the nodejs repository script
  ansible.builtin.file:
    path: /tmp/node_repo_setup
    state: absent
  when: not node.stat.exists

- name: install nodejs packages
  ansible.builtin.package:
    name: "{{ nodejs_packages }}"
    state: present

- name: install needed packages from npm
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ npm_packages }}"
