---
- name: Include variables for Node.js-related tasks
  ansible.builtin.include_vars:
    file: nodejs.yml

- name: Install node.js
  ansible.builtin.package:
    name: "{{ nodejs_packages }}"
    state: present

- name: Install npm packages
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ npm_packages }}"
