---
- name: Send ONM configuration (parameters.yml)
  ansible.builtin.template:
    src: templates/onm_parameters.yml.j2
    dest: /home/opennemas/shared/app/config/parameters.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Delete doctrine cache
    - Reload php-fpm

- name: Send ONM configuration (connections.yml)
  ansible.builtin.template:
    src: templates/onm_connections.yml.j2
    dest: /home/opennemas/shared/app/config/connections.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Delete doctrine cache
    - Reload php-fpm
