---
- name: add appworker users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    groups: www-data
    append: yes
    shell: /bin/bash
    state: present
  loop:
    "{{ appworker_users }}"
  no_log: yes

- name: set authorized key for appworker users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.pubkey }}"
  loop:
    "{{ appworker_users }}"

- name: add sudo privileges to appworker users
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/common
    create: yes
    mode: "0400"
    state: present
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}  {{ item.sudo_permissions }}"
  loop:
    "{{ appworker_users }}"
