---
- include_vars: vault_appworker_users.yml
- include_vars: appworker_users.yml

- name: Add appworker users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    groups: www-data
    shell: /bin/bash
    state: present
  loop:
    "{{ appworker_users }}"

- name: Set authorized key for Opennemas users
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.pubkey }}"
  loop:
    "{{ appworker_users }}"

- name: Add sudo privileges to appworker users
  lineinfile:
    path: /etc/sudoers.d/common
    create: yes
    state: present
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}  ALL=(ALL:ALL) /bin/chmod, /bin/chown, /bin/chgrp, /usr/sbin/service php7.3-fpm reload"
  loop:
    "{{ appworker_users }}"
    