---
php_cli_ini:
  - regexp: "serialize_precision ="
    line: "serialize_precision = 17"
  - regexp: "memory_limit ="
    line: "memory_limit = 512M"
  - regexp: "default_charset ="
    line: ";default_charset = \"UTF-8\""
  - regexp: "mail.add_x_header ="
    line: "mail.add_x_header = On"

php_fpm_ini:
  - regexp: "serialize_precision ="
    line: "serialize_precision = 17"
  - regexp: "expose_php ="
    line: "expose_php = On"
  - regexp: "max_execution_time ="
    line: "max_execution_time = 60"
  - regexp: "memory_limit"
    line: "memory_limit = 512M"
  - regexp: "post_max_size ="
    line: "post_max_size = 20M"
  - regexp: "default_charset ="
    line: ";default_charset = \"UTF-8\""
  - regexp: "upload_max_filesize ="
    line: "upload_max_filesize = 20M"
  - regexp: "mail.add_x_header ="
    line: "mail.add_x_header = On"

php_fpm_conf:
  - regexp: "emergency_restart_threshold ="
    line: "emergency_restart_threshold = 10"
  - regexp: "emergency_restart_interval ="
    line: "emergency_restart_interval = 1m"
  - regexp: "process_control_timeout ="
    line: "process_control_timeout = 5s"

php_www_conf:
  - regexp: "listen.backlog ="
    line: "listen.backlog = 65535"
  - regexp: "pm ="
    line: "pm = ondemand"
  - regexp: "pm.max_children ="
    line: "pm.max_children = 50"
  - regexp: "pm.process_idle_timeout ="
    line: "pm.process_idle_timeout = 5s;"
  - regexp: "pm.max_requests ="
    line: "pm.max_requests = 1500"
  - regexp: "pm.status_path ="
    line: "pm.status_path = /status"
  - regexp: "request_terminate_timeout ="
    line: "request_terminate_timeout = 60s"
  - regexp: "rlimit_files ="
    line: "rlimit_files = 131072"
  - regexp: "rlimit_core ="
    line: "rlimit_core = unlimited"
  - regexp: "chdir ="
    line: "chdir = /"

php_opcache_ini:
  - regexp: "opcache.enable="
    line: "opcache.enable=1"
  - regexp: "opcache.enable_cli="
    line: "opcache.enable_cli=0"
  - regexp: "opcache.memory_consumption="
    line: "opcache.memory_consumption=256"
  - regexp: ";opcache.interned_strings_buffer="
    line: ";opcache.interned_strings_buffer=128"
  - regexp: "opcache.max_accelerated_files="
    line: "opcache.max_accelerated_files=50000"
  - regexp: "opcache.revalidate_freq="
    line: "opcache.revalidate_freq=5"
  - regexp: "opcache.fast_shutdown="
    line: "opcache.fast_shutdown=1"
  - regexp: "opcache.max_wasted_percentage="
    line: "opcache.max_wasted_percentage=5"
  - regexp: "opcache.use_cwd="
    line: "opcache.use_cwd=1"
  - regexp: "opcache.validate_timestamps="
    line: "opcache.validate_timestamps=1"
