---
dependencies:
  - role: geerlingguy.nfs
    vars:
      nfs_exports:
        - "/srv/shared/instances   *(rw,fsid=1,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
        - "/srv/shared/media       *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
        - "/srv/shared/build       *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
        - "/srv/shared/spool       *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
        - "/srv/shared/backup      *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"