---
dependencies:
  - role: gabops.papertrail
    vars:
      papertrail_version: "0.20"
      papertrail_service_enabled: true
      papertrail_service_state: started
      papertrail_check_download_certs: true
      papertrail_managed_conf_file: true
      papertrail_managed_conf_file_owner: root
      papertrail_managed_conf_file_group: root
      papertrail_managed_conf_file_mode: "0644"
      papertrail_managed_conf_file_backup: false
      papertrail_custom_hostname: ""
      papertrail_destination_host: "{{ onm_papertrail_destination_host }}"
      papertrail_destination_port: "{{ onm_papertrail_destination_port }}"
      papertrail_destination_protocol: "{{ onm_papertrail_destination_protocol }}"
      papertrail_log_facility: ""
      papertrail_log_severity: ""
      papertrail_new_file_check_interval: ""
      papertrail_exclude_patterns: []
      papertrail_files_to_exclude: []
      papertrail_files_to_log: "{{ onm_papertrail_files_to_log }}"