---
- name: install nginx-extras package
  ansible.builtin.apt:
    name: nginx-extras
    state: present
    update_cache: yes

- name: configure nginx (nginx.conf)
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx service

# - name: configure nginx (vhosts-includes)
#   ansible.builtin.copy:
#     src: files/vhosts-includes
#     dest: /etc/nginx/
#     owner: root
#     group: root
#     mode: "0644"
#   notify: reload nginx service

- name: disable default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx service

# If netdata is installed the site configurations are different,
# so this check must be run beforehand
- name: check if netdata is installed
  ansible.builtin.stat:
    path: /opt/netdata/usr/sbin/netdata
  register: nd

- name: configure netdata nginx plugin (nginx.conf)
  ansible.builtin.template:
    src: templates/netdata_nginx.conf.j2
    dest: /opt/netdata/etc/netdata/python.d/nginx.conf
    owner: netdata
    group: netdata
    mode: "0644"
  when: nd.stat.exists
  notify: restart netdata service

- name: configure netdata php-fom plugin (phpfpm.conf)
  ansible.builtin.template:
    src: templates/netdata_phpfpm.conf.j2
    dest: /opt/netdata/etc/netdata/python.d/phpfpm.conf
    owner: netdata
    group: netdata
    mode: "0644"
  when: nd.stat.exists
  notify: restart netdata service

- name: add `status` page for netdata access (fpm/pool.d/www.conf)
  ansible.builtin.lineinfile:
    path: /etc/php/7.3/fpm/pool.d/www.conf
    regexp: "pm.status_path ="
    line: "pm.status_path = /status"
    state: present
  when: nd.stat.exists
  notify: reload php-fpm

# - name: configure `manager` site
#   ansible.builtin.template:
#     src: templates/sites/manager.j2
#     dest: /etc/nginx/sites-available/manager
#     owner: root
#     group: root
#     mode: "0644"
#   notify: reload nginx service

# - name: enable `manager` site
#   ansible.builtin.file:
#     src: /etc/nginx/sites-available/manager
#     dest: /etc/nginx/sites-enabled/manager
#     owner: root
#     group: root
#     state: link
#   notify: reload nginx service

- name: send example index file for `my_web` site
  ansible.builtin.template:
    src: templates/index.php.j2
    dest: "/home/{{ cert_name }}/current/public/index.php"
    owner: www-data
    group: www-data
    mode: "0644"

- name: configure `my_web` site
  ansible.builtin.template:
    src: templates/sites/my_web.j2
    dest: /etc/nginx/sites-available/my_web
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx service

- name: enable `my_web` site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/my_web
    dest: /etc/nginx/sites-enabled/my_web
    owner: root
    group: root
    state: link
  notify: reload nginx service
