---
# Cloud-dependant backupninja configuration

# /etc/backupninja.conf
when: hourly

# /etc/backup.d/10_database_dump.mysql
sqldumpoptions: --lock-tables --complete-insert --add-drop-table --quick --quote-names --single-transaction
