---
- name: Reload nginx service
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Reload varnish services
  ansible.builtin.service:
    name: "{{ item }}"
    state: reloaded
    daemon_reload: yes
  loop:
    - varnish
    - varnishncsa

- name: Restart varnish service
  ansible.builtin.service:
    name: varnish
    state: restarted
    daemon_reload: yes

- name: Restart netdata service
  ansible.builtin.service:
    name: netdata
    state: restarted
