---
- name: Set cron jobs
  cron:
    name: "{{ item.name | default ('') }}"
    minute: "{{ item.minute | default ('*') }}"
    hour: "{{ item.hour | default ('*') }}"
    day: "{{ item.day | default ('*') }}"
    month: "{{ item.month | default ('*') }}"
    weekday: "{{ item.weekday | default ('*') }}"
    user: "{{ item.user | default ('www-data') }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default ('present') }}"
    disabled: "{{ item.disabled | default ('no') }}"
    cron_file: "{{ item.cron_file | default ('onm-default') }}"
  loop:
    "{{ cronjobs }}"


