---
- name: add mailing directive to onm-default cron file
  ansible.builtin.lineinfile:
    path: /etc/cron.d/onm-default
    create: yes
    regexp: "^MAILTO( )*="
    line: "MAILTO={{ cron_mailto }}"
    insertbefore: BOF

- name: set cron jobs
  ansible.builtin.cron:
    name: "{{ item.name | default ('') }}"
    minute: "{{ item.minute | default ('*') }}"
    hour: "{{ item.hour | default ('*') }}"
    day: "{{ item.day | default ('*') }}"
    month: "{{ item.month | default ('*') }}"
    weekday: "{{ item.weekday | default ('*') }}"
    user: "{{ item.user | default ('www-data') }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default ('present') }}"
    disabled: "{{ item.disabled | default ('no') }}"
    cron_file: "{{ item.cron_file | default ('onm-default') }}"
  loop:
    "{{ cronjobs }}"
