---
- name: Include logrotate role
  ansible.builtin.include_role:
    name: arillso.logrotate
  vars:
    logrotate_global_config: false
    logrotate_applications:
      - name: "cron_{{ cert_name }}"
        definitions:
          - logs:
              - "/home/{{ cert_name }}/shared/tmp/logs/cron.log"
            options:
              - su www-data www-data
              - maxsize 500M
              - compress
              - compresscmd /bin/gzip
              - dateext
              - daily
              - rotate 7
              - missingok
              - copytruncate
