---
- name: install essential packages
  ansible.builtin.package:
    name: "{{ essential_packages }}"
    state: present

- name: Extra packages tasks
  ansible.builtin.import_tasks: extra_packages.yml

- name: set timezone to utc
  timezone:
    name: Etc/UTC

- name: generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    "{{ locales }}"

- name: User tasks
  ansible.builtin.import_tasks: users.yml

- name: Sysctl tasks
  ansible.builtin.import_tasks: sysctl.yml

- name: Shell files tasks
  ansible.builtin.import_tasks: shell_files.yml

- name: Netdata tasks
  ansible.builtin.import_tasks: netdata.yml
