- name: install essential packages
  import_tasks: packages.yml

- name: set timezone to utc
  timezone:
    name: Etc/UTC

- name: generate locales
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - gl_ES.UTF-8
    - es_ES.UTF-8
    - ca_ES.UTF-8

