- include_vars: main.yml

- name: install essential packages
  import_tasks: packages.yml

- name: set timezone to utc
  timezone:
    name: Etc/UTC

- name: generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    "{{ locales }}"

- name: create admin users
  import_tasks: users.yml

