---
- name: set timezone to utc
  timezone:
    name: Etc/UTC

- name: generate locales
  locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    "{{ locales }}"

- name: Swap tasks
  ansible.builtin.import_tasks: swap.yml

- name: Packages tasks
  ansible.builtin.import_tasks: packages.yml

- name: User tasks
  ansible.builtin.import_tasks: users.yml

- name: Sysctl tasks
  ansible.builtin.import_tasks: sysctl.yml

- name: Shell files tasks
  ansible.builtin.import_tasks: shell_files.yml

- name: Netdata tasks
  ansible.builtin.import_tasks: netdata.yml
