---
- name: check if netdata is already installed
  ansible.builtin.stat:
    path: /opt/netdata/usr/sbin/netdata
  register: nd

- name: download netdata installation script
  ansible.builtin.get_url:
    url: https://my-netdata.io/kickstart-static64.sh
    dest: /tmp/kickstart-static64.sh
    checksum: md5:c735fd724be5726c8a1850deed2793b8
  run_once: yes
  delegate_to: localhost
  when: not nd.stat.exists
  become: no

- name: send netdata installation script
  ansible.builtin.copy:
    src: /tmp/kickstart-static64.sh
    dest: /tmp/kickstart-static64.sh
    owner: root
    group: root
    mode: "0500"
  when: not nd.stat.exists

# The --dont-start-it flags prevents later problems, by delegating the task of starting the
# service to the role playbooks, after proper configuration of the netdata service.
# If started right after installation, restarting the service after sending new
# configurations results in a failed start.
- name: run the netdata installation script
  ansible.builtin.command:
    cmd: /tmp/kickstart-static64.sh --stable-channel --no-updates --dont-wait --dont-start-it
  when: not nd.stat.exists

- name: delete the netdata installation script
  ansible.builtin.file:
    path: /tmp/kickstart-static64.sh
    state: absent
  when: not nd.stat.exists

- name: configure netdata (netdata.conf)
  ansible.builtin.template:
    src: templates/netdata.conf.j2
    dest: /opt/netdata/etc/netdata/netdata.conf
    owner: netdata
    group: netdata
    mode: "0644"
  notify: restart netdata service

- name: configure netdata (stream.conf)
  ansible.builtin.template:
    src: templates/stream.conf.j2
    dest: /opt/netdata/etc/netdata/stream.conf
    owner: netdata
    group: netdata
    mode: "0644"
  notify: restart netdata service
