---
- name: include shell files variables
  ansible.builtin.include_vars: shell_files.yml

- name: copy shell files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    "{{ shell_files }}"
