- name: enable conntrack modules
  modprobe:
    name: nf_conntrack
    state: present

- name: persist enabling conntrack modules
  copy:
    dest: /etc/modules-load.d/nf_conntrack.conf
    content:
      nf_conntrack

- name: set sysctl values
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    "{{ sysctl_values }}"
