---
- name: add admin users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    state: present
  loop:
    "{{ admin_users }}"

- name: set authorized keys for users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.pubkey }}"
  loop:
    "{{ admin_users }}"
