- include_vars: users.yml

- name: add admin users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    uid: "{{ item.uid }}"
    group: sudo
    state: present
  loop:
    "{{ admin_users }}"

- name: remove old users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  loop:
    "{{ old_users }}"
