---
- name: set up directories for nfs service
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
  loop:
    "{{ nfs_directories }}"

- name: set sysctl values
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    "{{ sto_sysctl_values }}"

- name: Configure statd port options
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-common
    regexp: "STATDOPTS"
    line: "STATDOPTS=--port 32765 --outgoing-port 32766"

- name: Configure RPC port options
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-kernel-server
    regexp: "RPCMOUNTDOPTS"
    line: "RPCMOUNTDOPTS=--manage-gids -p 32767"
