---
- name: Inlcude variables for nfs-related tasks
  ansible.builtin.include_vars: nfs.yml

- name: Create directories for nfs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
  loop:
    "{{ nfs_directories }}"

- name: Include nfs role
  ansible.builtin.include_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports:
      - "/srv/shared/instances   *(rw,fsid=1,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
      - "/srv/shared/media       *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
      - "/srv/shared/build       *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
      - "/srv/shared/spool       *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"
      - "/srv/shared/backup      *(rw,async,no_subtree_check,all_squash,anonuid=33,anongid=33)"

- name: set sysctl values
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    "{{ nfs_sysctl_values }}"

- name: Configure statd port options
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-common
    regexp: "STATDOPTS"
    line: "STATDOPTS=--port 32765 --outgoing-port 32766"

- name: Configure RPC port options
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-kernel-server
    regexp: "RPCMOUNTDOPTS"
    line: "RPCMOUNTDOPTS=--manage-gids -p 32767"
