---
- name: Reload nginx service
  service:
    name: nginx
    state: reloaded

- name: Reload php-fpm
  service:
    name: php7.3-fpm
    state: reloaded

- name: Restart netdata service
  service:
    name: netdata
    state: restarted
