---
# postfix configuration variables for worker nodes
postfix_config:
  recipient_user: root
  recipient: support@my_app.es
  relayhost: smtp.acumbamail.com
  relayport: 25
  smtp_tls_security_level: none
  sasl_user: my_app.es@gmail.com
  sasl_pass: "{{ vault_sasl_pass }}"
  compatibility_level: 2
