---
# Full arquitechture playbook

# Run the common role for all nodes simultaneously
- hosts: all
  roles:
    - common

####################################################

- hosts: dbr
  pre_tasks:
    - name: stop nosql tasks if no nosql nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no nosql nodes defined in the dbr group!
          The play will stop.
          % % % % % % % %

      when: "groups.dba | length == 0"

    - name: stop nosql tasks if no nosql nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no nosql nodes defined in the dbr group!
          The play will stop.
          % % % % % % % %

      when: "groups.dba | length == 0"

  roles:
    - redis

####################################################

- hosts: sto
  pre_tasks:
    - name: stop storage tasks if no storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no storage nodes defined in the sto group!
          The play will stop.
          % % % % % % % %

      when: "groups.sto | length == 0"

    - name: stop storage tasks if more than one storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are multiple storage nodes defined in the sto group!
          Only one storage node is supported at the time. The play will stop.
          % % % % % % % %

      when: "groups.sto | length > 1"

  roles:
    - storage

####################################################

- hosts: dba
  pre_tasks:
    - name: stop database tasks if no database nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no database nodes defined in the dba group!
          The play will stop.
          % % % % % % % %

      when: "groups.dba | length == 0"

    - name: warn about not having high availability
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There's only one database node defined.
          This does not guarantee High Availability!
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.dba | length < 2"

    - name: warn about possible quorum issues when even number of database nodes defined in hosts
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There's an even number of database nodes defined.
          You may run into quorum issues.
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.dba | length % 2  == 0"

  roles:
    - database

####################################################

- hosts: sbl
  pre_tasks:
    - name: stop database tasks if no sql balancing nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          There are no SQL balancing nodes defined in the sbl group!
          The play will stop.
          % % % % % % % %

      when: "groups.sbl | length == 0"

    - name: warn if no database nodes defined in hosts
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          There are no database nodes defined in the dba group!
          No database nodes will be defined in the ProxySQL configuration.
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.dba | length == 0"

    - name: warn about not having high availability
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There's only one SQL balancing node defined.
          This does not guarantee High Availability!
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.sbl | length < 2"

  roles:
    - sqlbalancer

####################################################

# Run the appworker role for all app and wrk nodes simultaneously,
# avoiding running the appworker role twice.
- hosts: appwrk
  pre_tasks:
    - name: stop application and worker tasks if no application nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          There are no application nodes defined in the app group!
          The play will stop.
          % % % % % % % %

      when: "(groups.app | length == 0) or (groups.wrk | length == 0)"

    - name: stop application tasks if no storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no storage nodes defined in the sto group!
          The play will stop.
          % % % % % % % %

      when: "groups.sto | length == 0"

    - name: stop application tasks if more than one storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are multiple storage nodes defined in the sto group!
          Only one storage node is supported at the time. The play will stop.
          % % % % % % % %

      when: "groups.sto | length > 1"

    - name: warn about not having high availability
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There's only one application node defined.
          This does not guarantee High Availability!
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.app | length < 2"

  roles:
    - appworker

####################################################

- hosts: app
  pre_tasks:
    - name: stop application tasks if no application nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          There are no application nodes defined in the app group!
          The play will stop.
          % % % % % % % %

      when: "groups.app | length == 0"

    - name: stop application tasks if no storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no storage nodes defined in the sto group!
          The play will stop.
          % % % % % % % %

      when: "groups.sto | length == 0"

    - name: stop application tasks if more than one storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are multiple storage nodes defined in the sto group!
          Only one storage node is supported at the time. The play will stop.
          % % % % % % % %

      when: "groups.sto | length > 1"

    - name: warn about not having high availability
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There's only one application node defined.
          This does not guarantee High Availability!
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.app | length < 2"

  roles:
    - app

####################################################

- hosts: wrk
  pre_tasks:
    - name: stop worker tasks if no worker nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no worker nodes defined in the wrk group!
          The play will stop.
          % % % % % % % %

      when: "groups.wrk | length == 0"

    - name: stop worker tasks if no storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are no storage nodes defined in the sto group!
          The play will stop.
          % % % % % % % %

      when: "groups.sto | length == 0"

    - name: stop application tasks if more than one storage nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          WARNING! There are multiple storage nodes defined in the sto group!
          Only one storage node is supported at the time. The play will stop.
          % % % % % % % %

      when: "groups.sto | length > 1"

  roles:
    - worker

####################################################

- hosts: lbl
  pre_tasks:
    - name: stop loadbalancer tasks if no application nodes defined in hosts
      ansible.builtin.fail:
        msg: |

          % % % % % % % %
          WARNING! There are no load balancing nodes defined in the lbl group!
          The play will stop.
          % % % % % % % %

      when: "groups.lbl | length == 0"

    - name: warn if no application nodes defined in hosts
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There are no application nodes defined in the app group!
          No application nodes will be defined in the Varnish configuration.
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.app | length == 0"

    - name: warn about not having high availability
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There's only one load balancing node defined.
          This does not guarantee High Availability!
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.lbl | length < 2"

  roles:
    - loadbalancer

# The PLAY RECAP should be reporting at least 1 change in database servers
# (because of permission modification for mysql users,
# always reporting changes)
