---
# myapp general playbook

# Run the common role for all nodes simultaneously
- hosts: all
  roles:
    - common

- hosts: dbr
  roles:
    - redis

- hosts: sto
  roles:
    - storage

- hosts: dba
  roles:
    - database

- hosts: sbl
  roles:
    - proxysql

# Run the appworker role for all app and wrk nodes simultaneously,
# avoiding running the appworker role twice.
- hosts: appwrk
  roles:
    - appworker

- hosts: app
  roles:
    - app

- hosts: wrk
  roles:
    - worker

- hosts: lbl
  roles:
    - loadbalancer

# The PLAY RECAP should be reporting at least 1 change in database servers
# (because of permission modification for mysql the myapp-instances user,
# always reporting changes)
