---
# ONM general playbook

# Run the common role for all nodes simultaneously
- hosts: all
  roles:
    - common

- hosts: dbr
  roles:
    - redis

- hosts: sto
  roles:
    - storage

- hosts: dba
  roles:
    - database

# Run the appworker role for all app and wrk nodes simultaneously,
# avoiding running the appworker role twice.
- hosts: appwrk
  roles:
    - appworker

- hosts: app
  roles:
    - app

- hosts: wrk
  roles:
    - worker

- hosts: lbl
  roles:
    - loadbalancer

# The PLAY RECAP should be reporting at least 2 changes in database servers
# (because of permission modification for mysql users, always reporting changes),
# and 3? changes in worker servers (because the execution of the netdata
# installation script through the non-idempotent `command` module)
