---
- hosts: sbl
  pre_tasks:
    - name: stop database tasks if no sql balancing nodes defined in hosts
      ansible.builtin.fail:
        prompt: |

          % % % % % % % %
          There are no SQL balancing nodes defined in the sbl group!
          The play will stop.
          % % % % % % % %

      when: "groups.sbl | length == 0"

    - name: warn if no database nodes defined in hosts
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          There are no database nodes defined in the dba group!
          No database nodes will be defined in the ProxySQL configuration.
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.dba | length == 0"

    - name: warn about not having high availability
      ansible.builtin.pause:
        prompt: |

          % % % % % % % %
          WARNING! There's only one SQL balancing node defined.
          This does not guarantee High Availability!
          % % % % % % % %

          Press <Enter> to continue, or <Ctrl + C> to stop the play
      when: "groups.sbl | length < 2"

  roles:
    - common
    - proxysql
