---
backupninja_conf:
  - directive: "loglevel"
    value: "3"
  - directive: "reportemail"
    value: "support@openhost.es"
  - directive: "reportsuccess"
    value: "yes"
  # - directive: "#reportinfo"
  #   value: "no"
  - directive: "reportwarning"
    value: "yes"
  # - directive: "#reportspace"
  #   value: "no"
  - directive: "reporthost"
    value: ""
  - directive: "reportuser"
    value: "backup"
  - directive: "reportdirectory"
    value: "/var/lib/backupninja/reports"
  # - directive: "#admingroup"
  #   value: "root"
  - directive: "logfile"
    value: "/var/log/backupninja.log"
  - directive: "configdirectory"
    value: "/etc/backup.d"
  - directive: "scriptdirectory"
    value: "/usr/share/backupninja"
  - directive: "libdirectory"
    value: "/usr/lib/backupninja"
  - directive: "usecolors"
    value: "yes"
  - directive: "when"
    value: "{{ when }}"
  - directive: "vservers"
    value: "no"
