---
redis_daemon: redis-server
redis_port: 6379
redis_bind_interface: 0.0.0.0
redis_tcp_keepalive: 60
redis_unixsocket: ''
redis_timeout: 300

redis_loglevel: "notice"
redis_logfile: /var/log/redis/redis-server.log

redis_databases: 16

# Set to an empty set to disable persistence (saving the DB to disk).
redis_save: []
  # - 900 1
  # - 300 10
  # - 60 10000

redis_slowlog_max_len: 128

redis_rdbcompression: "yes"
redis_dbfilename: dump.rdb
redis_dbdir: /var/lib/redis

# Redis needs memory in bytes, Ansible gets memory in megabytes
# The previous value for maxmemory was 7516192768
# Usually, the value for maxmemory should be (totalmemory - 1.5gb)
# So, the calculations go like this:
# maxmemory = host_memory*1000000 - 1500000000
redis_maxmemory: "{{ ansible_facts.memtotal_mb*900000 }}"    # 90% of total
# TODO: sacar a variable de host ("{{ redis_host_maxmemory }}"?), valor por defecto -> sobreescribir
redis_maxmemory_policy: "allkeys-lru"
redis_maxmemory_samples: 5

redis_appendonly: "no"
redis_appendfsync: "everysec"

# Add extra include files for local configuration/overrides.
redis_includes: []

# Require authentication to Redis with a password.
redis_requirepass: ""

# Disable certain Redis commands for security reasons.
redis_disabled_commands: []
#  - FLUSHDB
#  - FLUSHALL
#  - KEYS
#  - PEXPIRE
#  - DEL
#  - CONFIG
#  - SHUTDOWN
#  - BGREWRITEAOF
#  - BGSAVE
#  - SAVE
#  - SPOP
#  - SREM
#  - RENAME
#  - DEBUG
